config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  patch '/bookings/:id/approve', to: 'bookings#change_status_approve', as: 'booking_approve'
  patch '/bookings/:id/decline', to: 'bookings#change_status_decline', as: 'booking_decline'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flowers do
    resources :bookings, only: [ :new, :create ]
   end

  resources :bookings, only: [:show, :index]
  resources :flower_shops, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flower
end

app/models/flower.rb
class Flower < ApplicationRecord
  SPECIES = ["Rose", "Cactuc", "Lily", "Tulip", "Pione", "Gladiolus Larkspur", "Azalea", "Moth orchids", "Coneflower", "Touch-me-not", "Lily of the Nile", "Cactus", "Sweet pea"]
  has_one_attached :picture
  belongs_to :flower_shop
  has_many :bookings
  validates :name, presence: true
  validates :species, presence: true, inclusion: {in: SPECIES}
  validates :total_price, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_species,
  against: [ :name, :species ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/flower_shop.rb
class FlowerShop < ApplicationRecord
  belongs_to :user
  has_one_attached :picture
  has_many :flowers
  has_many :bookings, through: :flowers
  geocoded_by :address
  validates :name, presence: true
  validates :address, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :flower_shop, dependent: :destroy
  has_many :bookings, through: :flower_shop

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def owner?
    !flower_shop.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    # if we want to edit / update / etc, add in params here
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    if current_user.owner?
      @bookings = current_user.flower_shop.bookings
    else
      @bookings = Booking.where(user: current_user)
    end
  end

  def show
    @booking = Booking.find(params[:id])
    # bookings --> i need the flower id, flowershop id and user id
  end

  def new
    @flower = Flower.find(params[:flower_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @flower = Flower.find(params[:flower_id])
    @booking.flower = @flower
    @booking.booking_status = "pending"
    @booking.user = current_user

    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def change_status_approve
    @booking = Booking.find(params[:id])
    @booking.booking_status = "Approved"
    @booking.save
    redirect_to bookings_path
  end
  def change_status_decline
    @booking = Booking.find(params[:id])
    @booking.booking_status = "Declined"
    @booking.save
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:pick_up_date)
  end

end

app/controllers/flower_shops_controller.rb
class FlowerShopsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def index
    @flower_shops = FlowerShop.all
  end

  def show
    @flower_shop = FlowerShop.find(params[:id])
    @flowers = @flower_shop.flowers
  end

  def new
    @flower_shop = FlowerShop.new
  end

  def create
    @flower_shop = FlowerShop.new(flower_shop_params)
    @flower_shop.user = current_user
    if @flower_shop.save!
      redirect_to @flower_shop, notice: 'You shop was successfully created...'
    else
      render :new
    end
  end

  private

  def flower_shop_params
    params.require(:flower_shop).permit(:name, :address, :picture)
  end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_flower, only: [:show, :edit, :update, :destroy]

def index
   if params[:query].present?
     @flowers = Flower.search_by_name_and_species(params[:query])
   else
     @flowers = Flower.all
   end
   @flower_shops = FlowerShop.all
   @markers = @flower_shops.map do |flower_shop|
      {
        lat: flower_shop.latitude,
        lng: flower_shop.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { flower: flower_shop }),
        image_url: helpers.asset_url('44-440344_blue-flower-transparent-png-clip-art-image-african')
      }
    end
 end

  def show
  end

  def create
    @flower = Flower.new(flower_params)
    @flower.flower_shop = current_user.flower_shop
    if @flower.save!
      redirect_to @flower, notice: 'You flower was successfully created.'
    else
      render :new
    end
  end

  def update
    if @flower.update(flower_params)
      redirect_to @flower, notice: 'Flower was successfully updated.'
    else
      render :edit
    end
  end

  def edit
  end

  def new
    @flower = Flower.new
  end

  def destroy
    @flower.destroy
    redirect_to flowers_path, notice: "Your flower has been destroyed!"
  end

  private

  def set_flower
    @flower = Flower.find(params[:id])
  end

  def flower_params
    params.require(:flower).permit(:name, :species, :address, :picture, :total_price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @flowers = Flower.order(created_at: :desc).limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
 <%= simple_form_for [@flower, @booking] do |f| %>
    <%= f.input :pick_up_date, as: :date, order: [:day, :month, :year], label: "Pickup date" %>
    <%= f.submit %>
  <% end %>

app/views/bookings/_show.html.erb
<!-- bookings -->
<h1> Your bookings </h1>

<%= render 'form', booking: @booking %>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/index.html.erb
<!-- bookings -->
<div class="row justify-content-center">
    <div class="card-product-show">
        <div class="card-product-infos">
            <% @bookings.each do |booking| %>
            <div class="card-product-infos">
                <ul>
                    <h5>
                        <li>
                            Pick up date: <%= booking.pick_up_date.strftime("%A %b %d, %Y") %> |
                            <%= booking.flower.name %> |
                            <%= booking.user.email %> |
                            <% if booking.booking_status == "pending" && current_user.flower_shop == booking.flower.flower_shop %>
                <%= link_to "Approve", booking_approve_path(booking), method: :patch, class: "btn btn-outline-light form-button" %>
                <%= link_to "Decline", booking_decline_path(booking), method: :patch, class: "btn btn-outline-light form-button" %>
                <% else %>
                <%= booking.booking_status %>
                <% end %>
                        </li>
                    </h5>
                </ul>
            </div>
            <% end %>
        </div>
    </div>
</div>
<br>
<div class="row justify-content-center">
    <%= link_to 'back to flower shop', flowers_path, class: "btn btn-outline-light form-button" %>
</div>

app/views/bookings/new.html.erb
<div align="center">
<div class="new-form">
    <h2>New Flower</h2>
    <%= render 'form', booking: @booking %>

app/views/flower_shops/_form.html.erb
<%= simple_form_for @flower_shop do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :picture, as: :file %>
    <%= f.submit %>
  <% end %>

app/views/flower_shops/index.html.erb
<%= render 'shared/banner'%>
<div class="main-container">
    <!-- Cards -->
    <div class="shop-cards">
      <% @flower_shops.each do |flower_shop| %>
        <%= link_to flower_shop_path(flower_shop) do %>
          <div class="shop-card">
            <div class="shop-card-img" id="img" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('https://source.unsplash.com/300x300/?flowershop');">
            </div>
            <div class="shop-card-info">
                <h2>
                  <%= flower_shop.name %>
                </h2>
                <p>
                  <%= flower_shop.address %>
                </p>
              <br>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>



<div
  id="map"
  style="
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

app/views/flower_shops/new.html.erb
<div align="center">
<div class="new-form">
    <h2>New FlowerShop</h2>
    <%= render 'form', flower_shop: @flower_shop %>
</div>
   <%= link_to 'Back', flowers_path, class: "btn btn-outline-light form-button" %>
</div>

app/views/flower_shops/show.html.erb
<div class="card-product-show-shop">
    <h1>
        <%= @flower_shop.name %>
    </h1>
    <h4>
      <%= @flower_shop.address %>
    </h4>
    <div class="d-flex">
      <div class="row">
        <% @flower_shop.flowers.each do |flower| %>
          <%= link_to flower_path(flower) do %>
            <div class="card-product-infos">
            <% if flower.picture.attached? %>
              <div class="card-product" id="img" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%=  cl_image_path flower.picture.key %>');">
                <h5>
                  <%= flower.name %>
                </h5>
                <p>
                  <%= flower.species %>
                </p>
              </div>
            <% else %>
              <div class="card-product" id="img" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('https://source.unsplash.com/featured/?flower, <%= flower.name %>');">
                <h5>
                  <%= flower.name %>
                </h5>
                <p>
                  <%= flower.species %>
                </p>
              </div>
            <% end %>
            </div>
          <% end %>
        <% end %>
        </div>
    </div>
    <% if current_user == @flower_shop.user %>
    <%= link_to "add a flower", new_flower_path, class: "btn btn-outline-light btn-shop" %>
    <% end %>
</div>
    <%= link_to 'Back', flowers_path, class: "btn btn-outline-light btn-shop" %>

app/views/flowers/_form.html.erb
<%= simple_form_for @flower do |f| %>
    <%= f.input :name %>
    <%= f.input :species, collection: Flower::SPECIES, as: :select %>

    <%= f.input :picture, as: :file %>

    <%= f.input :total_price, label: "€" %>

    <%= f.submit %>
  <% end %>

app/views/flowers/_info_window.html.erb
<h2><%= flower.name %></h2>
<p><%= flower.address %></p>

app/views/flowers/create.html.erb
<h1>Flowers#create</h1>
<p>Find me in app/views/flowers/create.html.erb</p>

app/views/flowers/edit.html.erb
<div align="center">
<div class="new-form">
<h1>Edit flower</h1>
<%= render 'form', flower: @flower %>
<hr>
<%= link_to flower_path do %>
<% end %>
</div>
         <%= link_to 'Back', flowers_path, class: "btn btn-outline-light form-button" %>
</div>

app/views/flowers/index.html.erb
<%= render 'shared/banner'%>
<div class="main-container">
    <!-- Cards -->

    <div class="cards">
      <% @flower_shops.each do |flower_shop| %>
            <%= link_to flower_shop_path(flower_shop) do %>
            <div class="card-product-infos">
                <% if flower_shop.picture.attached? %>
                <div class="card-product" id="img" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%=  cl_image_path flower_shop.picture.key %>');">
                    <% else %>
                    <div class="card-product" id="img" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('https://source.unsplash.com/featured/?flower, <%= flower_shop.name %>');">
                        <% end %>
                        <h5>
                            <%= flower_shop.name %>
                        </h5>
                        <p>
                            <%= flower_shop.address %>
                        </p>
                        <br>
                    </div>
                  </div>
              <% end %>
          <% end %>
        </div>

<div
  id="map"
  style="
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

app/views/flowers/new.html.erb
<div align="center">
<div class="new-form">
    <h2>New Flower</h2>
    <%= render 'form', flower: @flower %>
</div>
   <%= link_to 'Back', flowers_path, class: "btn btn-outline-light form-button" %>
</div>

app/views/flowers/new.htmn.erb
<div>
    <h2>New Flower</h2>
    <%= render 'form', flower: @flower %>
    <%= link_to 'Back', flowers_path %>
</div>

app/views/flowers/show.html.erb
<div class="d-flex justify-content-center align-items-center">
  <div class="container">
<div class="card-product-show">
    <% if @flower.picture.attached? %>
    <%= cl_image_tag(@flower.picture.key, width: 400, height: 300, crop: :fill) %>
    <% else %>
    <img src="https://source.unsplash.com/featured/?flower, <%= @flower.name %>" alt="Flower Picture">
    <% end %>
    <div class="card-product-infos">
        <h2 class="showtextborders">
            <%= @flower.name %>
        </h2>
        <h6>
            <%= @flower.species %>
        </h6>
        <h6>
            <%= @flower.total_price %>
        </h6>

        <p>
          A Cactus (plural cacti, cactuses, or less commonly, cactus) is a member of the plant family Cactaceae, a family comprising about 127 genera with some 1750 known species of the order Caryophyllales. The word "cactus" derives, through Latin, from the Ancient Greek κάκτος, kaktos, a name originally used by Theophrastus for a spiny plant whose identity is now not certain. Cacti occur in a wide range of shapes and sizes. Most cacti live in habitats subject to at least some drought. Many live in extremely dry environments, even being found in the Atacama Desert, one of the driest places on earth.
        </p>
    </div>
    <div class="show-buttons">
                <%= link_to 'Back', flower_shop_path(@flower.flower_shop), class: "btn btn-outline-light buttons" %>
                  <% if user_signed_in? %>
                  <% if @flower.flower_shop == current_user.flower_shop %>
                <%= link_to 'Edit', edit_flower_path(@flower.id), class: "btn btn-outline-light buttons" %>
                <%= link_to 'Delete', flower_path(@flower), method: :delete, class: "btn btn-outline-light buttons" %>
                  <% end %>
                  <% else %>
                <%= link_to 'Book this flower', new_flower_booking_path(@flower),  class: "btn btn-outline-light buttons" %>
                  <% end %>
                <%= link_to 'Visit this shop', flower_shop_path(@flower.flower_shop), class: "btn btn-outline-light buttons" %>
    </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='icon' href='https://cdn.dribbble.com/users/2442548/screenshots/5142105/illustrations_cacti_round_2x.png' type='image/x-icon'/ >
    <title>FlowerFriend</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>

<body>
    <%= render 'shared/navbar'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="content">
    <%= yield %>
    </div>
    <%= render 'shared/footer'%>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
</body>

</html>

app/views/pages/home.html.erb
<div class="homebanner">
    <div class="container">
    <!-- <h1 class="flowerfriendtext">🅵🅻🅾🆆🅴🆁 🅵🆁🅸🅴🅽🅳</h1> -->
    <form action="/flowers" method="GET">
      <input class= "btn-lg btn-light nav-btn" type="submit" name="commit" value="Discover..." >
    </form>
  </div>
 </div>


<div class="wrapper">
  <img src="https://source.unsplash.com/random/600x600?water" alt="">
  <img src="https://source.unsplash.com/random/600x600?summer" alt="">
  <img src="https://source.unsplash.com/random/600x600?plants" alt="">
  <img src="https://source.unsplash.com/random/600x600?snow" alt="">
  <img src="https://source.unsplash.com/random/600x600?roses" alt="">
  <img src="https://source.unsplash.com/random/600x600?sky" alt="">
  <img src="https://source.unsplash.com/random/600x600?nature" alt="">
  <img src="https://source.unsplash.com/random/600x600?blossom" alt="">
  <img src="https://source.unsplash.com/random/600x600?ice" alt="">
  <img src="https://source.unsplash.com/random/600x600?spring" alt="">
</div>

app/views/shared/_banner.html.erb
 <div class="banner">
    <div class="container">
    <p>Bring nature inside</p>
    <form action="/flowers" method="GET">
    <input class="btn btn-outline-light" type="text" name="query" id="query" placeholder="Search flower…">
    <input class="btn btn-outline-light" type="submit" name="commit" value="Search">
    </form>
<!--     <button type="button" class="btn btn-outline-light">Search for your next flower</button> -->
  </div>
 </div>





<!-- <div class="text-container">
    <form action="/flowers" method="GET">
        <input type="text" name="query" id="query" placeholder="Search flower…">
        <input type="submit" name="commit" value="Search">
    </form>
</div> -->

app/views/shared/_cards.html.erb
<div class="custom-border-top my-3"></div>
    <div class="cards">
        <div class="card-product" id="img" style="background-image: linear-gradient(rgba(255,255,255,0.1), rgba(255,255,255,0.1)), url('https://images.unsplash.com/photo-1557968581-06d4b39ec0d6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80');">
            <div class="card-product-infos">
              <h2>Peony</h2>
          </div>
        </div>

        <div class="card-product" id="img" style="background-image: linear-gradient(rgba(255,255,255,0.1), rgba(255,255,255,0.1)), url('https://images.unsplash.com/photo-1507236827745-1dbaaeb68a3e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80');">
           <!--  <%= link_to "show_flower", class: "button" %> -->
            <div class="card-product-infos">
              <h2>Cactus</h2>
          </div>
        </div>

        <div class="card-product" id="img" style="background-image: linear-gradient(rgba(255,255,255,0.1), rgba(255,255,255,0.1)), url('https://images.unsplash.com/photo-1568569028884-e802596e7528?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80');">
            <div class="card-product-infos">
              <h2>Hydrangea</h2>
          </div>
        </div>

        <div class="card-product" id="img" style="background-image: linear-gradient(rgba(255,255,255,0.1), rgba(255,255,255,0.1)), url('https://images.unsplash.com/photo-1572688484438-313a6e50c333?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=667&q=80');">
            <div class="card-product-infos">
              <h2>Spiderplant</h2>
          </div>
        </div>

    </div>
<br>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
        We <i class="fas fa-heart"></i> flowers
    </div>
</div>

app/views/shared/_map.html.erb
<div
  id="map"
  style="height: 100vh; width: 400px; position: sticky; top: 0px; background-color: rgb(229, 227, 223);"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand home-button" do %>
    <%= image_tag "https://cdn.dribbble.com/users/2442548/screenshots/5142105/illustrations_cacti_round_2x.png" %>
    <% end %>
    <h4>🅵🅻🅾🆆🅴🆁 🅵🆁🅸🅴🅽🅳</h4>
      <br>
      <br>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    <form action="/flowers" method="GET">
    <input class="btn btn-outline-light nav-btn" type="text" name="query" id="query" placeholder="Search flower…">
    <input class="btn btn-outline-light nav-btn" type="submit" name="commit" value="Search">
    </form>


      <% if user_signed_in? %>
        <li class="nav-item options">
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://source.unsplash.com/50x50/?head", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
           <% if current_user.flower_shop %>
            <%= link_to "your flower shop", flower_shop_path(current_user), class: "dropdown-item" %>
            <%= link_to "see all bookings", bookings_path, class: "dropdown-item" %>
          <% else %>
            <%= link_to "+ add shop", new_flower_shop_path, class: "btn btn-outline-light nav-btn" %>
          <% end %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <%= current_user.email %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>

  </div>
</div>